version: '3'

services:
  mock-ec2-metadata:
    image: public.ecr.aws/aws-ec2/amazon-ec2-metadata-mock:v1.11.2
  mock-localstack:
    image: docker.io/localstack/localstack:3
    environment:
    - SERVICES=kinesis,s3,cloudwatch,es,firehose,sqs,sns,logs
  s3.mock-localstack:
    image: docker.io/localstack/localstack:3
    environment:
    - SERVICES=kinesis,s3,cloudwatch,es,firehose,sqs,sns,logs
    extra_hosts:
      - "vhost-test.s3.mock-localstack:127.0.0.1"
  mock-ecs:
    image: docker.io/amazon/amazon-ecs-local-container-endpoints:latest
    volumes:
    - $DOCKER_SOCKET:/var/run/docker.sock
    - $HOME/.aws/:/home/.aws/
